patterns:
  - talib_fn: CDLDOJI
    label: Doji
    priority: 1
  - talib_fn: CDLSPINNINGTOP
    label: SpinningTop
    priority: 2
  - talib_fn: CDLENGULFING
    label: BullishEngulfing
    priority: 3
  - talib_fn: CDLENGULFING
    label: BearishEngulfing
    priority: 3
  - talib_fn: CDLHAMMER
    label: Hammer
    priority: 4

min_abs_value: 50              # lesser means more sensitive detection
allow_negative: true           # keep bearish patterns too (negative values)