# Model configuration
model:
  type: "resnet34"
  num_classes: 5             
  pretrained: true            

# ViT configuration
vit:
  type: "deit_tiny_pretrained"  #["lightweight", "deit_tiny_pretrained"]
  params:
    image_size: 224
    patch_size: 16          # revert to 16x16 (better generalization observed)

# Data configuration
data:
  image_size: 224           
  batch_size: 32            
  num_workers: 4             
  pin_memory: true          

# Training configuration
training:
  num_epochs: 60            
  learning_rate: 3e-4         # Learning rate for CNN
  vit_learning_rate: 3e-5     # Learning rate for ViT

  # weight decay for CNN
  cnn_weight_decay: 1e-4          # for CNN stability

  # weight decay for ViT
  vit_weight_decay: 5e-5          # for ViT stability
  gradient_clip: 1.0          # for ViT training
  
  # Learning rate scheduling
  scheduler:
    type: "cosine"      #["cosine", "step"]       
    warmup_epochs: 10     
    min_lr: 1e-7    
  
  # Early stopping
  early_stopping:
    patience: 10           
    min_delta: 0.001 
  
  # Loss function
  loss:
    type: "weighted_ce"       
    label_smoothing: 0.05    

# Validation configuration
validation:
  frequency: 1                
  save_best: true             
  
# Model saving
model_saving:
  save_dir_cnn: "models/cnn_large"          
  save_dir_vit: "models/vit_deit_pretrained"
  save_frequency: 5           
  keep_last: 3                
  
# Hardware configuration
hardware:
  device: "auto"              # "auto", "cuda", or "cpu"
  mixed_precision: true       
  deterministic: false        
  memory_efficient: true     

# Logging and monitoring
logging:
  log_frequency: 10       
  tensorboard: true         
  wandb: false             
  
# Evaluation metrics
metrics:
  primary: "f1_macro"        
  secondary: ["accuracy", "precision", "recall"]
